services:
  - type: web
    name: 2rsnotas-backend
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromSecret: database-url
      - key: CERT_KEY
        fromSecret: cert-key
      - key: CORS_ORIGINS
        value: "*"
    autoDeploy: true